const devConfig = {
  apiKey: "1-2-3-4",
  session: "header.payload.signature",
  settings: {
    customer_id: "1",
    sample: 1,
    hosts: {
      host: "staging.fastly-insights.com",
      lookup: "u.staging.eu.fastly-insights.com",
      pop: "pops.staging.fastly-insights.com"
    }
  },
  build: "http://localhost:3001/dist/lib.js",
  server: {
    datacenter: "LHR"
  },
  tasks: [],
  pops: [
    {
      neighbours: ["YUL", "ORD", "JFK", "MSP"],
      others: [
        "IAD",
        "BOS",
        "ATL",
        "DFW",
        "DEN",
        "MIA",
        "SEA",
        "SJC",
        "LAX",
        "LCY",
        "LHR",
        "AMS",
        "CDG",
        "HHN",
        "FRA",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "ITM",
        "HKG",
        "FJR",
        "AKL",
        "SYD",
        "WLG",
        "BNE",
        "SIN",
        "AKL",
        "MEL",
        "JNB",
        "PER"
      ],
      pop: "YYZ"
    },
    {
      neighbours: ["MIA", "JFK", "BOS", "ATL"],
      others: [
        "IAD",
        "ORD",
        "YUL",
        "DFW",
        "MSP",
        "YYZ",
        "DEN",
        "LAX",
        "SEA",
        "SJC",
        "LHR",
        "LCY",
        "HHN",
        "AMS",
        "FRA",
        "CDG",
        "MAD",
        "BMA",
        "NRT",
        "ITM",
        "AKL",
        "AKL",
        "WLG",
        "SYD",
        "HKG",
        "FJR",
        "BNE",
        "MEL",
        "JNB",
        "SIN",
        "PER"
      ],
      pop: "GRU"
    },
    {
      neighbours: ["HKG", "PER", "NRT", "ITM"],
      others: [
        "MEL",
        "SYD",
        "FJR",
        "BNE",
        "AKL",
        "WLG",
        "LAX",
        "SJC",
        "AKL",
        "CDG",
        "MAD",
        "FRA",
        "LCY",
        "LHR",
        "SEA",
        "HHN",
        "AMS",
        "DEN",
        "DFW",
        "BMA",
        "ATL",
        "ORD",
        "MSP",
        "YYZ",
        "MIA",
        "IAD",
        "JFK",
        "BOS",
        "YUL",
        "JNB",
        "GRU"
      ],
      pop: "SIN"
    },
    {
      neighbours: ["LCY", "AMS", "CDG", "FRA"],
      others: [
        "HHN",
        "MAD",
        "BMA",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "YYZ",
        "ORD",
        "ATL",
        "MSP",
        "MIA",
        "FJR",
        "DFW",
        "DEN",
        "SEA",
        "LAX",
        "SJC",
        "JNB",
        "GRU",
        "SIN",
        "HKG",
        "NRT",
        "AKL",
        "AKL",
        "ITM",
        "SYD",
        "WLG",
        "BNE",
        "MEL",
        "PER"
      ],
      pop: "LHR"
    },
    {
      neighbours: ["JFK", "YUL", "IAD", "ORD"],
      others: [
        "YYZ",
        "ATL",
        "MSP",
        "MIA",
        "DFW",
        "DEN",
        "LCY",
        "LHR",
        "SEA",
        "AMS",
        "CDG",
        "LAX",
        "SJC",
        "HHN",
        "FRA",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "FJR",
        "ITM",
        "WLG",
        "AKL",
        "AKL",
        "SYD",
        "HKG",
        "JNB",
        "BNE",
        "MEL",
        "SIN",
        "PER"
      ],
      pop: "BOS"
    },
    {
      neighbours: ["SIN", "ITM", "NRT", "FJR"],
      others: [
        "SYD",
        "MEL",
        "PER",
        "BNE",
        "AKL",
        "AKL",
        "SEA",
        "WLG",
        "LAX",
        "SJC",
        "DEN",
        "ORD",
        "DFW",
        "YYZ",
        "JFK",
        "IAD",
        "MSP",
        "LHR",
        "ATL",
        "HHN",
        "YUL",
        "FRA",
        "BOS",
        "MIA",
        "BMA",
        "LCY",
        "MAD",
        "CDG",
        "AMS",
        "GRU",
        "JNB"
      ],
      pop: "HKG"
    },
    {
      neighbours: ["ITM", "HKG", "SIN", "SEA"],
      others: [
        "LAX",
        "SJC",
        "SYD",
        "BNE",
        "AKL",
        "DEN",
        "ORD",
        "AKL",
        "WLG",
        "DFW",
        "JFK",
        "BOS",
        "ATL",
        "MSP",
        "YYZ",
        "FJR",
        "PER",
        "IAD",
        "MIA",
        "YUL",
        "MEL",
        "LHR",
        "HHN",
        "LCY",
        "MAD",
        "AMS",
        "CDG",
        "FRA",
        "BMA",
        "GRU",
        "JNB"
      ],
      pop: "NRT"
    },
    {
      neighbours: ["LAX", "SEA", "DEN", "DFW"],
      others: [
        "ORD",
        "MSP",
        "ATL",
        "YYZ",
        "MIA",
        "IAD",
        "JFK",
        "YUL",
        "BOS",
        "NRT",
        "ITM",
        "AKL",
        "AKL",
        "LCY",
        "LHR",
        "WLG",
        "CDG",
        "FRA",
        "AMS",
        "HKG",
        "HHN",
        "MAD",
        "SIN",
        "BNE",
        "BMA",
        "MEL",
        "GRU",
        "SYD",
        "PER",
        "FJR",
        "JNB"
      ],
      pop: "SJC"
    },
    {
      neighbours: ["LCY", "LHR", "HHN", "FRA"],
      others: [
        "CDG",
        "BMA",
        "MAD",
        "BOS",
        "JFK",
        "YUL",
        "IAD",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "DFW",
        "DEN",
        "FJR",
        "LAX",
        "SEA",
        "SJC",
        "JNB",
        "SIN",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "WLG",
        "AKL",
        "HKG",
        "SYD",
        "MEL",
        "BNE",
        "PER"
      ],
      pop: "AMS"
    },
    {
      neighbours: ["BOS", "IAD", "YUL", "YYZ"],
      others: [
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "DFW",
        "DEN",
        "SEA",
        "LCY",
        "LHR",
        "LAX",
        "SJC",
        "CDG",
        "AMS",
        "FRA",
        "HHN",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "FJR",
        "ITM",
        "AKL",
        "WLG",
        "SYD",
        "AKL",
        "HKG",
        "MEL",
        "BNE",
        "JNB",
        "SIN",
        "PER"
      ],
      pop: "JFK"
    },
    {
      neighbours: ["HHN", "FRA", "AMS", "LCY"],
      others: [
        "LHR",
        "CDG",
        "MAD",
        "JFK",
        "YUL",
        "IAD",
        "BOS",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "FJR",
        "DFW",
        "DEN",
        "SEA",
        "LAX",
        "SJC",
        "JNB",
        "SIN",
        "GRU",
        "HKG",
        "NRT",
        "AKL",
        "ITM",
        "AKL",
        "SYD",
        "WLG",
        "MEL",
        "BNE",
        "PER"
      ],
      pop: "BMA"
    },
    {
      neighbours: ["SJC", "DEN", "LAX", "DFW"],
      others: [
        "ORD",
        "MSP",
        "YYZ",
        "ATL",
        "JFK",
        "MIA",
        "IAD",
        "BOS",
        "YUL",
        "NRT",
        "ITM",
        "LHR",
        "LCY",
        "AMS",
        "HHN",
        "AKL",
        "FRA",
        "AKL",
        "CDG",
        "BMA",
        "MAD",
        "HKG",
        "WLG",
        "GRU",
        "SIN",
        "MEL",
        "BNE",
        "SYD",
        "PER",
        "FJR",
        "JNB"
      ],
      pop: "SEA"
    },
    {
      neighbours: ["MEL", "BNE", "AKL", "AKL"],
      others: [
        "WLG",
        "PER",
        "SIN",
        "HKG",
        "LAX",
        "DEN",
        "DFW",
        "SJC",
        "ORD",
        "ATL",
        "SEA",
        "YYZ",
        "MSP",
        "JFK",
        "IAD",
        "MIA",
        "BOS",
        "YUL",
        "NRT",
        "LCY",
        "LHR",
        "FRA",
        "ITM",
        "AMS",
        "FJR",
        "HHN",
        "CDG",
        "BMA",
        "MAD",
        "GRU",
        "JNB"
      ],
      pop: "SYD"
    },
    {
      neighbours: ["HHN", "AMS", "CDG", "LCY"],
      others: [
        "LHR",
        "BMA",
        "MAD",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "DFW",
        "FJR",
        "MSP",
        "DEN",
        "SJC",
        "LAX",
        "SEA",
        "JNB",
        "SIN",
        "GRU",
        "HKG",
        "NRT",
        "ITM",
        "AKL",
        "AKL",
        "SYD",
        "WLG",
        "MEL",
        "BNE",
        "PER"
      ],
      pop: "FRA"
    },
    {
      neighbours: ["ATL", "IAD", "DFW", "JFK"],
      others: [
        "ORD",
        "BOS",
        "YUL",
        "MSP",
        "DEN",
        "YYZ",
        "LAX",
        "SJC",
        "SEA",
        "LCY",
        "LHR",
        "AMS",
        "FRA",
        "GRU",
        "HHN",
        "CDG",
        "MAD",
        "BMA",
        "ITM",
        "NRT",
        "AKL",
        "AKL",
        "FJR",
        "WLG",
        "SYD",
        "MEL",
        "BNE",
        "SIN",
        "HKG",
        "PER",
        "JNB"
      ],
      pop: "MIA"
    },
    {
      neighbours: ["DFW", "ORD", "SEA", "SJC"],
      others: [
        "MSP",
        "LAX",
        "ATL",
        "YYZ",
        "MIA",
        "IAD",
        "JFK",
        "YUL",
        "BOS",
        "LHR",
        "LCY",
        "AMS",
        "FRA",
        "HHN",
        "CDG",
        "MAD",
        "NRT",
        "BMA",
        "ITM",
        "AKL",
        "GRU",
        "AKL",
        "WLG",
        "SYD",
        "MEL",
        "HKG",
        "BNE",
        "SIN",
        "PER",
        "FJR",
        "JNB"
      ],
      pop: "DEN"
    },
    {
      neighbours: ["SJC", "SEA", "DFW", "DEN"],
      others: [
        "ATL",
        "ORD",
        "MIA",
        "IAD",
        "MSP",
        "JFK",
        "YYZ",
        "BOS",
        "YUL",
        "NRT",
        "ITM",
        "LHR",
        "LCY",
        "CDG",
        "AMS",
        "FRA",
        "HHN",
        "SYD",
        "AKL",
        "MEL",
        "BNE",
        "HKG",
        "WLG",
        "AKL",
        "MAD",
        "SIN",
        "GRU",
        "BMA",
        "PER",
        "FJR",
        "JNB"
      ],
      pop: "LAX"
    },
    {
      neighbours: ["MEL", "SYD", "SIN", "BNE"],
      others: [
        "AKL",
        "AKL",
        "WLG",
        "HKG",
        "LAX",
        "NRT",
        "SJC",
        "SEA",
        "DFW",
        "DEN",
        "ATL",
        "ORD",
        "MIA",
        "IAD",
        "JFK",
        "MSP",
        "YYZ",
        "BOS",
        "YUL",
        "FJR",
        "ITM",
        "LCY",
        "LHR",
        "FRA",
        "HHN",
        "CDG",
        "AMS",
        "MAD",
        "BMA",
        "GRU",
        "JNB"
      ],
      pop: "PER"
    },
    {
      neighbours: ["SIN", "LHR", "LCY", "CDG"],
      others: [
        "HKG",
        "HHN",
        "FRA",
        "AMS",
        "MAD",
        "BMA",
        "NRT",
        "ITM",
        "BOS",
        "JFK",
        "YUL",
        "IAD",
        "ATL",
        "ORD",
        "MIA",
        "YYZ",
        "MSP",
        "DFW",
        "DEN",
        "SJC",
        "LAX",
        "SEA",
        "JNB",
        "PER",
        "MEL",
        "SYD",
        "BNE",
        "AKL",
        "WLG",
        "GRU",
        "AKL"
      ],
      pop: "FJR"
    },
    {
      neighbours: ["LHR", "AMS", "CDG", "FRA"],
      others: [
        "HHN",
        "MAD",
        "BMA",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "FJR",
        "DFW",
        "DEN",
        "SEA",
        "LAX",
        "SJC",
        "JNB",
        "GRU",
        "SIN",
        "NRT",
        "AKL",
        "ITM",
        "HKG",
        "SYD",
        "WLG",
        "BNE",
        "MEL",
        "AKL",
        "PER"
      ],
      pop: "LCY"
    },
    {
      neighbours: ["WLG", "SYD", "MEL", "BNE"],
      others: [
        "PER",
        "SIN",
        "SJC",
        "NRT",
        "HKG",
        "ITM",
        "SEA",
        "LAX",
        "DEN",
        "DFW",
        "ATL",
        "ORD",
        "IAD",
        "MSP",
        "MIA",
        "BOS",
        "JFK",
        "YUL",
        "YYZ",
        "LHR",
        "HHN",
        "AMS",
        "FRA",
        "BMA",
        "GRU",
        "LCY",
        "CDG",
        "MAD",
        "FJR",
        "JNB"
      ],
      pop: "AKL"
    },
    {
      neighbours: ["LHR", "LCY", "AMS", "CDG"],
      others: [
        "FRA",
        "HHN",
        "MAD",
        "BMA",
        "JFK",
        "BOS",
        "IAD",
        "YUL",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "DFW",
        "DEN",
        "FJR",
        "SJC",
        "LAX",
        "SEA",
        "GRU",
        "SIN",
        "NRT",
        "HKG",
        "ITM",
        "WLG",
        "AKL",
        "AKL",
        "BNE",
        "MEL",
        "SYD",
        "PER"
      ],
      pop: "JNB"
    },
    {
      neighbours: ["FRA", "AMS", "CDG", "LHR"],
      others: [
        "LCY",
        "BMA",
        "MAD",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "YYZ",
        "ATL",
        "ORD",
        "MIA",
        "MSP",
        "DFW",
        "FJR",
        "DEN",
        "SEA",
        "LAX",
        "SJC",
        "JNB",
        "SIN",
        "GRU",
        "HKG",
        "NRT",
        "ITM",
        "AKL",
        "AKL",
        "WLG",
        "SYD",
        "MEL",
        "BNE",
        "PER"
      ],
      pop: "HHN"
    },
    {
      neighbours: ["ORD", "YYZ", "ATL", "DFW"],
      others: [
        "DEN",
        "JFK",
        "YUL",
        "IAD",
        "BOS",
        "MIA",
        "SEA",
        "SJC",
        "LAX",
        "LHR",
        "LCY",
        "CDG",
        "AMS",
        "HHN",
        "MAD",
        "FRA",
        "BMA",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "AKL",
        "FJR",
        "HKG",
        "SYD",
        "MEL",
        "SIN",
        "BNE",
        "WLG",
        "JNB",
        "PER"
      ],
      pop: "MSP"
    },
    {
      neighbours: ["CDG", "LCY", "LHR", "FRA"],
      others: [
        "HHN",
        "AMS",
        "BMA",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "ORD",
        "ATL",
        "YYZ",
        "MIA",
        "MSP",
        "DFW",
        "FJR",
        "DEN",
        "SEA",
        "SJC",
        "LAX",
        "SIN",
        "JNB",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "WLG",
        "HKG",
        "AKL",
        "SYD",
        "BNE",
        "MEL",
        "PER"
      ],
      pop: "MAD"
    },
    {
      neighbours: ["DEN", "ATL", "ORD", "MSP"],
      others: [
        "MIA",
        "LAX",
        "IAD",
        "YYZ",
        "JFK",
        "SJC",
        "SEA",
        "BOS",
        "YUL",
        "LCY",
        "LHR",
        "CDG",
        "AMS",
        "HHN",
        "FRA",
        "MAD",
        "BMA",
        "GRU",
        "ITM",
        "NRT",
        "AKL",
        "AKL",
        "WLG",
        "SYD",
        "MEL",
        "BNE",
        "HKG",
        "SIN",
        "FJR",
        "PER",
        "JNB"
      ],
      pop: "DFW"
    },
    {
      neighbours: ["SYD", "BNE", "AKL", "AKL"],
      others: [
        "PER",
        "WLG",
        "SIN",
        "HKG",
        "LAX",
        "SJC",
        "DEN",
        "SEA",
        "DFW",
        "NRT",
        "ATL",
        "MIA",
        "ORD",
        "IAD",
        "MSP",
        "JFK",
        "YYZ",
        "BOS",
        "YUL",
        "ITM",
        "FJR",
        "LCY",
        "LHR",
        "AMS",
        "FRA",
        "HHN",
        "CDG",
        "BMA",
        "MAD",
        "GRU",
        "JNB"
      ],
      pop: "MEL"
    },
    {
      neighbours: ["YYZ", "JFK", "BOS", "IAD"],
      others: [
        "ORD",
        "ATL",
        "MSP",
        "MIA",
        "DFW",
        "DEN",
        "SEA",
        "SJC",
        "LCY",
        "LHR",
        "LAX",
        "AMS",
        "CDG",
        "HHN",
        "FRA",
        "BMA",
        "MAD",
        "GRU",
        "NRT",
        "ITM",
        "FJR",
        "AKL",
        "AKL",
        "WLG",
        "SYD",
        "HKG",
        "JNB",
        "BNE",
        "MEL",
        "SIN",
        "PER"
      ],
      pop: "YUL"
    },
    {
      neighbours: ["SYD", "MEL", "AKL", "AKL"],
      others: [
        "WLG",
        "PER",
        "SIN",
        "HKG",
        "LAX",
        "NRT",
        "SJC",
        "SEA",
        "DEN",
        "DFW",
        "ATL",
        "MIA",
        "ORD",
        "IAD",
        "MSP",
        "YYZ",
        "JFK",
        "BOS",
        "YUL",
        "ITM",
        "LCY",
        "LHR",
        "FJR",
        "HHN",
        "AMS",
        "CDG",
        "FRA",
        "BMA",
        "MAD",
        "GRU",
        "JNB"
      ],
      pop: "BNE"
    },
    {
      neighbours: ["JFK", "BOS", "ATL", "YUL"],
      others: [
        "ORD",
        "YYZ",
        "MIA",
        "DFW",
        "MSP",
        "DEN",
        "LAX",
        "SJC",
        "SEA",
        "LCY",
        "LHR",
        "CDG",
        "AMS",
        "FRA",
        "HHN",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "WLG",
        "FJR",
        "AKL",
        "SYD",
        "MEL",
        "BNE",
        "HKG",
        "JNB",
        "SIN",
        "PER"
      ],
      pop: "IAD"
    },
    {
      neighbours: ["IAD", "MIA", "ORD", "JFK"],
      others: [
        "DFW",
        "BOS",
        "MSP",
        "YYZ",
        "YUL",
        "DEN",
        "LAX",
        "SJC",
        "SEA",
        "LCY",
        "LHR",
        "AMS",
        "CDG",
        "FRA",
        "HHN",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "WLG",
        "AKL",
        "FJR",
        "SYD",
        "MEL",
        "BNE",
        "HKG",
        "SIN",
        "PER",
        "JNB"
      ],
      pop: "ATL"
    },
    {
      neighbours: ["LHR", "LCY", "FRA", "AMS"],
      others: [
        "HHN",
        "MAD",
        "BMA",
        "BOS",
        "JFK",
        "IAD",
        "YUL",
        "YYZ",
        "ATL",
        "ORD",
        "MSP",
        "MIA",
        "DFW",
        "DEN",
        "FJR",
        "LAX",
        "SJC",
        "SEA",
        "JNB",
        "SIN",
        "GRU",
        "NRT",
        "AKL",
        "ITM",
        "WLG",
        "HKG",
        "SYD",
        "MEL",
        "AKL",
        "BNE",
        "PER"
      ],
      pop: "CDG"
    },
    {
      neighbours: ["NRT", "HKG", "SIN", "LAX"],
      others: [
        "SJC",
        "SEA",
        "AKL",
        "DFW",
        "DEN",
        "MIA",
        "ORD",
        "IAD",
        "FJR",
        "ATL",
        "MSP",
        "JFK",
        "YYZ",
        "BOS",
        "YUL",
        "AKL",
        "BNE",
        "SYD",
        "WLG",
        "MEL",
        "LCY",
        "PER",
        "AMS",
        "LHR",
        "CDG",
        "FRA",
        "HHN",
        "MAD",
        "GRU",
        "BMA",
        "JNB"
      ],
      pop: "ITM"
    },
    {
      neighbours: ["MSP", "YYZ", "ATL", "IAD"],
      others: [
        "JFK",
        "BOS",
        "DFW",
        "YUL",
        "DEN",
        "MIA",
        "SEA",
        "SJC",
        "LAX",
        "LCY",
        "LHR",
        "CDG",
        "AMS",
        "HHN",
        "FRA",
        "MAD",
        "BMA",
        "GRU",
        "NRT",
        "ITM",
        "AKL",
        "HKG",
        "AKL",
        "WLG",
        "SYD",
        "BNE",
        "FJR",
        "MEL",
        "SIN",
        "PER",
        "JNB"
      ],
      pop: "ORD"
    }
  ],
  tasks: []
};

const dev = `
	var config = window.FASTLY.config || ${JSON.stringify(devConfig)};
`;

const prod = `
	var config = {
		apiKey: '<% APIKEY %>',
		session: '<% SESSION %>',
		settings: '<% CONFIG %>',
		build: '<% BUILD %>',
		server: '<% SERVER %>',
        tasks: '<% TASKS %>',
		pops: '<% POPS %>'
	};
`;

const esi = {
  apiKey: '<esi:include src="/esi/js/apikey.json" />',
  session: '<esi:include src="/esi/js/session.js" />',
  config: '<esi:include src="/esi/js/config.json" />',
  build: '<esi:include src="/esi/js/build.js" />',
  server: '<esi:include src="/esi/js/server.js" />',
  tasks: '<esi:include src="/esi/js/tasks.json" />',
  pops: '<esi:include src="/esi/js/neighbours.json" />'
};

module.exports = { dev, prod, esi };
